version: "2"

services:
  server:
    network_mode: "host"
    ports:
      - "8080:8080"
    build: server/build/docker
  client:
    network_mode: "host"
    ports:
      - "3000:3000"
    stdin_open: true
    build: client
  mongodb:
    network_mode: "host"
    ports:
      - "27017:27017"
    image: mongo:latest
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: